// Enum for auth navigator's route names
export enum AuthNav {
  LOGIN_WITH_EMAIL = 'LOGIN_WITH_EMAIL',
  LOGIN_WITH_NUMBER = 'LOGIN_WITH_NUMBER',
  SIGN_UP_WITH_EMAIL = 'SIGN_UP_WITH_EMAIL',
  SIGN_UP_WITH_NUMBER = 'SIGN_UP_WITH_NUMBER',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  ONBOARDING = 'ONBOARDING',
}
